name: Dawid Potocki's Blog
author: Dawid Potocki

domain: dawidpotocki.com
url: https://dawidpotocki.com
onion_domain: dawid26ccfg7igbsk6if6lya765nwac7jt4uefys3qilh3s4glw4eoyd.onion
mail_domain: mail.dawidpotocki.com
personal_mail:
  - "&#100;&#97;&#119;&#105;&#100;"
  - "&#64;"
  - "&#100;&#97;&#119;&#105;&#100;&#112;&#111;&#116;&#111;&#99;&#107;&#105;"
  - ".&#99;&#111;&#109;"


permalink: pretty
pagination:
  enabled: true
  debug: false
  collection: "posts"
  per_page: 8
  permalink: "/page/:num/"
  title: "Page :num "
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"


include:
  - .well-known

exclude:
  - README.md
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

sass:
  style: compressed
  sass_dir: ./assets/css

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/favicon/opengraph-600x600.png
